version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: production
    ports:
      - "3000"
    environment:
      SOLR_SEARCH_TWEAK_ENABLE: "on"
      SOLR_URL: "http://solr:8983/solr/blacklight"
      SOLR_AZ_URL: "http://solr:8983/solr/az-database"
      SOLR_WEB_CONTENT_URL: "http://solr:8983/solr/web-content"
      DO_INGEST: "${DO_INGEST}"
      LC_ALL: "C.UTF-8"
    networks:
      - "default"
    entrypoint:
      - ruby
      - /app/bin/app-start.rb
