version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  coveralls: coveralls/coveralls@1.0.6

workflows:
  version: 2
  debug:
    jobs:
      - debug_deploy
jobs:
  debug_deploy:
    docker:
      - image: circleci/python:3.6.6
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
            - "59:d3:45:4c:e5:31:4e:cd:64:c0:e3:2a:73:a3:55:94"
      - run:
          name: Set Production Airflow Variable "CATALOG_PRODUCTION_SOLR_COLLECTION" to match value in .env
          command: bash .circleci/update-airflow.sh
