default: &default
  sign_out_redirect_url: <%= ENV["IDP_REDIRECT_URL"] || "/Shibboleth.sso/Logout?return=https://fim.temple.edu/idp/profile/Logout" %>
  saml_certificate: |- <%= ENV["COB_SP_CERT"] %>
  saml_private_key: |- <%= ENV["COB_SP_KEY"] %>
  saml_issuer: "http://localhost:3000/users/auth/saml/metadata/212c43b2ba0f5c0e3d4d60ec67a7397947dc7808"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
