default: &default
  sign_out_redirect_url: <%= ENV["IDP_REDIRECT_URL"] || "/Shibboleth.sso/Logout?return=https://fim.temple.edu/idp/profile/Logout" %>
  saml_certificate: |- <%= ENV["COB_SP_CERT"] %>
  saml_private_key: |- <%= ENV["COB_SP_KEY"] %>
  saml_issuer: "https://librarysearch.k8s.temple.edu/users/auth/saml/metadata"
    #saml_issuer: "https://librarysearch.k8s.temple.edu/users/auth/saml/metadata"
  assertion_consumer_service_url: "https://librarysearch.k8s.temple.edu/users/auth/saml/callback"
    #assertion_consumer_service_url: "https://librarysearch.k8s.temple.edu/users/auth/saml/callback"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
