default: &default
  - title: "Author/Creator"
    query: "f%5Bcreator_facet%5D%5B%5D=Tufte%2C+Edward+R.%2C+1942-&sort=title_sort+asc%2C+pub_date_sort+desc"
  - title: "Call Number Asc."
    query: "f_1=all_fields&f_2=all_fields&f_3=all_fields&op_1=AND&op_2=AND&operator%5Bq_1%5D=contains&operator%5Bq_2%5D=contains&operator%5Bq_3%5D=contains&q_1=&q_2=&q_3=&range%5Blc_classification%5D%5Bbegin%5D=P93.5.T83x+1990&range%5Blc_classification%5D%5Bend%5D=&range%5Bpub_date_sort%5D%5Bbegin%5D=&range%5Bpub_date_sort%5D%5Bend%5D=&search_field=advanced&sort=lc_call_number_sort+asc%2C+pub_date_sort+des"
  - title: "Call Number Desc."
    query: "f_1=all_fields&f_2=all_fields&f_3=all_fields&op_1=AND&op_2=AND&operator%5Bq_1%5D=contains&operator%5Bq_2%5D=contains&operator%5Bq_3%5D=contains&q_1=&q_2=&q_3=&range%5Blc_classification%5D%5Bbegin%5D=&range%5Blc_classification%5D%5Bend%5D=P93.5.T83x+1990&range%5Bpub_date_sort%5D%5Bbegin%5D=&range%5Bpub_date_sort%5D%5Bend%5D=&search_field=advanced&sort=lc_call_number_sort+desc%2C+pub_date_sort+desc"
  - title: "New Books"
    query: "f%5Bformat%5D%5B%5D=Book&q=&search_field=all_fields&sort=pub_date_sort+desc%2C+title_sort+asc"
  - title: "New Videos"
    query: "f%5Bformat%5D%5B%5D=Video&q=&search_field=all_fields&sort=pub_date_sort+desc%2C+title_sort+asc"
  - title: "New Musical Scores"
    query: "f%5Bformat%5D%5B%5D=Score&q=&search_field=all_fields&sort=pub_date_sort+desc%2C+title_sort+asc"
  - title: "New Archival Materials"
    query: "f%5Bformat%5D%5B%5D=Archival+Material&q=&search_field=all_fields&sort=pub_date_sort+desc%2C+title_sort+asc"

development:
    *default

test:
    *default

production:
    *default
